# Generated by Django 2.2.19 on 2021-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211109_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='title', max_length=100, unique=True),
        ),
    ]
